//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyPremierLeague_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clubstatistiek
    {
        public int ClubstatsID { get; set; }
        public Nullable<int> Winst { get; set; }
        public Nullable<int> Gelijk { get; set; }
        public Nullable<int> Verlies { get; set; }
        public Nullable<int> DoelpuntVoor { get; set; }
        public Nullable<int> DoelpuntTegen { get; set; }
        public Nullable<int> Punten { get; set; }
        public int ClubID { get; set; }
        public int SeizoenID { get; set; }
    
        public virtual Club Clubs { get; set; }
        public virtual Seizoen Seizoenen { get; set; }
    }
}
