//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyPremierLeague_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PremierLeagueEntities : DbContext
    {
        public PremierLeagueEntities()
            : base("name=PremierLeagueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Clubstatistiek> Clubstats { get; set; }
        public virtual DbSet<Seizoen> Seizoenen { get; set; }
        public virtual DbSet<Speler> Spelers { get; set; }
        public virtual DbSet<Spelerstatistiek> Spelerstats { get; set; }
        public virtual DbSet<SpelerWedstrijd> SpelerWedstrijd { get; set; }
        public virtual DbSet<Wedstrijd> Wedstrijden { get; set; }
    }
}
