//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyPremierLeague_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seizoen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seizoen()
        {
            this.Clubstatistiek = new HashSet<Clubstatistiek>();
            this.Spelerstatistiek = new HashSet<Spelerstatistiek>();
            this.Wedstrijd = new HashSet<Wedstrijd>();
        }
    
        public int SeizoenID { get; set; }
        public string SeizoenNaam { get; set; }
        public System.DateTime Begindatum { get; set; }
        public System.DateTime Einddatum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clubstatistiek> Clubstatistiek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spelerstatistiek> Spelerstatistiek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijd> Wedstrijd { get; set; }
    }
}
