//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyPremierLeague_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Speler()
        {
            this.Spelerstat = new HashSet<Spelerstatistiek>();
            this.SpelerWedstrijd = new HashSet<SpelerWedstrijd>();
        }
    
        public int SpelerID { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Positie { get; set; }
        public string Shirtnummer { get; set; }
        public int ClubID { get; set; }
    
        public virtual Club Clubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spelerstatistiek> Spelerstat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpelerWedstrijd> SpelerWedstrijd { get; set; }
    }
}
