//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyPremierLeague_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spelerstatistiek
    {
        public int SpelerstatsID { get; set; }
        public Nullable<int> Doelpunt { get; set; }
        public Nullable<int> Assist { get; set; }
        public Nullable<int> GeleKaart { get; set; }
        public Nullable<int> RodeKaart { get; set; }
        public Nullable<int> Owngoal { get; set; }
        public int SpelerID { get; set; }
        public int SeizoenID { get; set; }
    
        public virtual Seizoen Seizoenen { get; set; }
        public virtual Speler Spelers { get; set; }
    }
}
