//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyPremierLeague_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedstrijd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wedstrijd()
        {
            this.SpelerWedstrijd = new HashSet<SpelerWedstrijd>();
        }
    
        public int WedstrijdID { get; set; }
        public int SeizoenID { get; set; }
        public int Speeldag { get; set; }
        public int ThuisClubID { get; set; }
        public Nullable<int> ThuisClubScore { get; set; }
        public Nullable<int> UitClubScore { get; set; }
        public int UitClubID { get; set; }
    
        public virtual Club ThuisClubs { get; set; }
        public virtual Club UitClubs { get; set; }
        public virtual Seizoen Seizoenen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpelerWedstrijd> SpelerWedstrijd { get; set; }
    }
}
