-- Arsenal

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bernd', 'Leno', 'D', '1', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Aaron', 'Ramsdale', 'D', '32', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Calum', 'Chambers', 'V', '21', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Gabriel', 'V', '6', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Rob', 'Holding', 'V', '16', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Sead', 'Kolasinac', 'V', '31', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ainsley', 'Maitland-Niles', 'V', '15', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pablo', 'Mari', 'V', '22', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Soares', 'Cedric', 'V', '17', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Taveres', 'Nuno', 'V', '20', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kieran', 'Tierney', 'V', '3', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Takehiro', 'Tomiyasu', 'V', '18', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ben', 'White', 'V', '4', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mohamed', 'Elneny', 'M', '25', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Sambi', 'Lokonga', 'M', '23', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Martin', 'Odegaard', 'M', '8', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Thomas', 'Partey', 'M', '5', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bukayo', 'Saka', 'M', '7', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Emile', 'Smith Rowe', 'M', '10', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Granit', 'Xhaka', 'M', '34', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pierre-Emerick', 'Aubameyang', 'A', '14', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Folarin', 'Balogun', 'A', '26', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Alexandre', 'Lacazette', 'A', '9', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Gabriel', 'Martinelli', 'A', '35', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Edward', 'Nketiah', 'A', '30', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nicolas', 'Pepe', 'A', '19', 1, 0, 0, 0, 0, 0)

--Aston Villa

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Emiliano', 'Martinez', 'D', '1', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jed', 'Steer', 'D', '12', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Matty', 'Cash', 'V', '2', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kortney', 'Hause', 'V', '30', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ezri', 'Konsa', 'V', '4', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tyrone', 'Mings', 'V', '5', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Matt', 'Targett', 'V', '3', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Axel', 'Tuanzebe ', 'V', '16', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Emiliano', 'Buendia', 'M', '10', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Carney', 'Chukwuemeka', 'M', '33', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Anwar', 'El-Ghazi', 'M', '21', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Douglas', 'Luiz', 'M', '6', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('John', 'McGinn', 'M', '7', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marvelous', 'Nakamba', 'M', '19', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jacob', 'Ramsey', 'M', '41', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Morgan', 'Sanson', 'M', '8', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ashley', 'Young', 'M', '18', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Cameron', 'Archer', 'A', '35', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Leon', 'Bailey', 'A', '31', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Keinan', 'Davis', 'A', '9', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Danny', 'Ings', 'A', '20', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jaden', 'Philogene-Bidace', '32', 'A', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bertrand', 'Traore', 'A', '15', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ollie', 'Watkins', 'A', '11', 2, 0, 0, 0, 0, 0)

--Brentford

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Fernandez', 'Alvaro', 'D', '40', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('David', 'Raya', 'D', '1', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kristoffer', 'Ajer', 'V', '20', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mads', 'Bech Sorensen', 'V', '29', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Charlie', 'Goode', 'V', '4', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Rico', 'Henry', 'V', '3', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pontus', 'Jansson', 'V', '18', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mathias', 'Jorgensen', 'V', '22', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ethan', 'Pinnock', 'V', '5', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mads', 'Roerslev Rasmussen', 'V', '30' 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Shandon', 'Baptiste', 'M', '26', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mads', 'Bidstrup', 'M', '28', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Sergi', 'Canos', 'M', '7', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Saman', 'Ghoddos', 'M', '14', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Vitaly', 'Janelt', 'M', '27', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mathias', 'Jensen', 'M', '8', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Christian', 'Norgaard', 'M', '6', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Frank', 'Onyeka', 'M', '15', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marcus', 'Forss', 'A', '9', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bryan', 'Mbeumo', 'A', '19', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ivan', 'Toney', 'A', '17', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Yoane', 'Wissa', 'A', '11', 3, 0, 0, 0, 0, 0)

--Brighton

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Robert', 'Sanchez', 'D', '1', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jason', 'Steele', 'D', '23', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Dan', 'Burn', 'V', '33', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marc', 'Cucurella', 'V', '3', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Shane', 'Duffy', 'V', '24', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Lewis', 'Dunk', 'V', '5', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tariq', 'Lamptey', 'V', '2', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joel', 'Veltman', 'V', '34', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Adam', 'Webster', 'V', '4', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Steven', 'Alzate', 'M', '17', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Yves', 'Bissouma', 'M', '8', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pascal', 'Gross', 'M', '13', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Adam', 'Lallana', 'M', '14', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Alexis', 'Mac Allister', 'M', '10', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Solomon', 'March', 'M', '20', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jakub', 'Moder', 'M', '15', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Enock', 'Mwepu', 'M', '12', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Taylor', 'Richards', 'M', '30', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jeremy', 'Sarmiento', 'M', '60', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Leandro', 'Trossard', 'M', '11', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Aaron', 'Connolly', 'A', '7', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jurgen', 'Locadia', 'A', '27', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Neal', 'Maupay', 'A', '9', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Danny', 'Welbeck', 'A', '18', 4, 0, 0, 0, 0, 0)

--Burnley

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nick', 'Pope', 'D', '1', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nathan Michael', 'Collins', 'V', '22', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Matthew', 'Lowton', 'V', '2', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ben', 'Mee', 'V', '6', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Erik', 'Pieters', 'V', '23', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Connor', 'Roberts', 'V', '14', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('James', 'Tarkowski', 'V', '5', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Charlie', 'Taylor', 'V', '3', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Josh', 'Brownhill', 'M', '8', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jack', 'Cork', 'M', '4', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Johann', 'Gudmundsson', 'M', '7', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Aaron', 'Lennon', 'M', '17', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Dwight', 'McNeil', 'M', '11', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ashley', 'Westwood', 'M', '18', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ashley', 'Barnes', 'A', '10', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Maxwel', 'Cornet', 'A', '20', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jay', 'Rodriguez ', 'A', '19', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Matej', 'Vydra', 'A', '27', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Chris', 'Wood', 'A', '9', 5, 0, 0, 0, 0, 0)

--Chelsea

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kepa', 'Arrizabalaga', 'D', '1', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Edouard', 'Mendy', 'D', '16', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marcos', 'Alonso', 'V', '3', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Cesar', 'Azpilicueta', 'V', '28', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Trevoh', 'Chalobah', 'V', '14', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ben', 'Chilwell', 'V', '21', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Andreas', 'Christensen', 'V', '4', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Reece', 'James', 'V', '24', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Antonio', 'Rudiger', 'V', '2', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Malang', 'Sarr', 'V', '31', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Thiago', 'Silva', 'V', '6', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ross', 'Barkley', 'M', '18', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kai', 'Havertz', 'M', '29', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Callum', 'Hudson-Odoi', 'M', '20', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Jorginho', 'M', '5', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ("N'Golo", 'Kante', 'M', '7', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mateo', 'Kovacic', 'M', '8', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ruben', 'Loftus-Cheek', 'M', '12', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mason', 'Mount', 'M', '19', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Saul', 'Niguez', 'M', '17', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Christian', 'Pulisic', 'M', '10', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Hakim', 'Ziyech', 'M', '22', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Romelu', 'Lukaku', 'A', '9', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Timo', 'Werner', 'A', '11', 6, 0, 0, 0, 0, 0)

--Crystal Palace

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', '', 'D', '', 7, 0, 0, 0, 0, 0)

