ALTER TABLE Seizoenen
ADD CONSTRAINT PK_Seizoen PRIMARY KEY (SeizoenID);

ALTER TABLE Clubs
ADD CONSTRAINT PK_Club PRIMARY KEY (ClubID);

ALTER TABLE Clubstats
ADD CONSTRAINT PK_Clubstats PRIMARY KEY (ClubstatsID),
ADD CONSTRAINT FK_ClubstatsClubID FOREIGN KEY (ClubID) REFERENCES Clubs(ClubID),
ADD CONSTRAINT FK_ClubstatsSeizoenID FOREIGN KEY (SeizoenID) REFERENCES Seizoenen(SeizoenID);

ALTER TABLE Spelers
ADD CONSTRAINT PK_Speler PRIMARY KEY (SpelerID),
ADD CONSTRAINT FK_SpelerClubID FOREIGN KEY (ClubID) REFERENCES Clubs(ClubID);

ALTER TABLE Spelerstats
ADD CONSTRAINT PK_Spelerstats PRIMARY KEY (SpelerstatsID),
ADD CONSTRAINT FK_SpelerstatsSpelerID FOREIGN KEY (SpelerID) REFERENCES Spelers(SpelerID),
ADD CONSTRAINT FK_SpelerstatsSeizoenID FOREIGN KEY (SeizoenID) REFERENCES Seizoenen(SeizoenID);

ALTER TABLE Wedstrijden
ADD CONSTRAINT PK_Wedstrijd PRIMARY KEY (WedstrijdID),
ADD CONSTRAINT FK_WedstrijdThuisClubID FOREIGN KEY (ThuisClubID) REFERENCES Clubs(ClubID),
ADD CONSTRAINT FK_WedstrijdUitClubID FOREIGN KEY (UitClubID) REFERENCES Clubs(ClubID),
ADD CONSTRAINT FK_WedstrijdSeizoenID FOREIGN KEY (SeizoenID) REFERENCES Seizoenen(SeizoenID);

ALTER TABLE SpelerWedstrijd
ADD CONSTRAINT PK_SpelerWedstrijd PRIMARY KEY (SpelerWedstrijdID),
ADD CONSTRAINT FK_SpelerWedstrijdSpelerID FOREIGN KEY (SpelerID) REFERENCES Spelers(SpelerID),
ADD CONSTRAINT FK_SpelerWedstrijdWedstrijdID FOREIGN KEY (WedstrijdID) REFERENCES Wedstrijden(WedstrijdID);

/* ALTER TABLE Datums
ADD CONSTRAINT PK_Datum PRIMARY KEY (DatumID);

ALTER TABLE DatumWedstrijd    
ADD CONSTRAINT PK_DatumWedstrijd PRIMARY KEY (DatumWedstrijdID),
ADD CONSTRAINT FK_DatumID FOREIGN KEY (DatumID) REFERENCES Datums(DatumID),
ADD CONSTRAINT FK_WedstrijdID FOREIGN KEY (WedstrijdID) REFERENCES Wedstrijden(WedstrijdID); */