-- Arsenal

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bernd', 'Leno', 'D', '1', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Aaron', 'Ramsdale', 'D', '32', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Calum', 'Chambers', 'V', '21', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Gabriel', 'V', '6', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Rob', 'Holding', 'V', '16', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Sead', 'Kolasinac', 'V', '31', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ainsley', 'Maitland-Niles', 'V', '15', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pablo', 'Mari', 'V', '22', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Soares', 'Cedric', 'V', '17', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Taveres', 'Nuno', 'V', '20', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kieran', 'Tierney', 'V', '3', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Takehiro', 'Tomiyasu', 'V', '18', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ben', 'White', 'V', '4', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mohamed', 'Elneny', 'M', '25', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Sambi', 'Lokonga', 'M', '23', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Martin', 'Odegaard', 'M', '8', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Thomas', 'Partey', 'M', '5', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bukayo', 'Saka', 'M', '7', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Emile', 'Smith Rowe', 'M', '10', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Granit', 'Xhaka', 'M', '34', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pierre-Emerick', 'Aubameyang', 'A', '14', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Folarin', 'Balogun', 'A', '26', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Alexandre', 'Lacazette', 'A', '9', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Gabriel', 'Martinelli', 'A', '35', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Edward', 'Nketiah', 'A', '30', 1, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nicolas', 'Pepe', 'A', '19', 1, 0, 0, 0, 0, 0)

--Aston Villa

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Emiliano', 'Martinez', 'D', '1', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jed', 'Steer', 'D', '12', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Matty', 'Cash', 'V', '2', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kortney', 'Hause', 'V', '30', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ezri', 'Konsa', 'V', '4', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tyrone', 'Mings', 'V', '5', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Matt', 'Targett', 'V', '3', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Axel', 'Tuanzebe ', 'V', '16', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Emiliano', 'Buendia', 'M', '10', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Carney', 'Chukwuemeka', 'M', '33', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Anwar', 'El-Ghazi', 'M', '21', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Douglas', 'Luiz', 'M', '6', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('John', 'McGinn', 'M', '7', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marvelous', 'Nakamba', 'M', '19', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jacob', 'Ramsey', 'M', '41', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Morgan', 'Sanson', 'M', '8', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ashley', 'Young', 'M', '18', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Cameron', 'Archer', 'A', '35', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Leon', 'Bailey', 'A', '31', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Keinan', 'Davis', 'A', '9', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Danny', 'Ings', 'A', '20', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jaden', 'Philogene-Bidace', '32', 'A', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bertrand', 'Traore', 'A', '15', 2, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ollie', 'Watkins', 'A', '11', 2, 0, 0, 0, 0, 0)

--Brentford

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Fernandez', 'Alvaro', 'D', '40', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('David', 'Raya', 'D', '1', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kristoffer', 'Ajer', 'V', '20', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mads', 'Bech Sorensen', 'V', '29', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Charlie', 'Goode', 'V', '4', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Rico', 'Henry', 'V', '3', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pontus', 'Jansson', 'V', '18', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mathias', 'Jorgensen', 'V', '22', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ethan', 'Pinnock', 'V', '5', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mads', 'Roerslev Rasmussen', 'V', '30', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Shandon', 'Baptiste', 'M', '26', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mads', 'Bidstrup', 'M', '28', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Sergi', 'Canos', 'M', '7', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Saman', 'Ghoddos', 'M', '14', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Vitaly', 'Janelt', 'M', '27', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mathias', 'Jensen', 'M', '8', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Christian', 'Norgaard', 'M', '6', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Frank', 'Onyeka', 'M', '15', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marcus', 'Forss', 'A', '9', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bryan', 'Mbeumo', 'A', '19', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ivan', 'Toney', 'A', '17', 3, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Yoane', 'Wissa', 'A', '11', 3, 0, 0, 0, 0, 0)

--Brighton

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Robert', 'Sanchez', 'D', '1', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jason', 'Steele', 'D', '23', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Dan', 'Burn', 'V', '33', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marc', 'Cucurella', 'V', '3', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Shane', 'Duffy', 'V', '24', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Lewis', 'Dunk', 'V', '5', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tariq', 'Lamptey', 'V', '2', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joel', 'Veltman', 'V', '34', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Adam', 'Webster', 'V', '4', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Steven', 'Alzate', 'M', '17', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Yves', 'Bissouma', 'M', '8', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pascal', 'Gross', 'M', '13', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Adam', 'Lallana', 'M', '14', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Alexis', 'Mac Allister', 'M', '10', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Solomon', 'March', 'M', '20', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jakub', 'Moder', 'M', '15', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Enock', 'Mwepu', 'M', '12', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Taylor', 'Richards', 'M', '30', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jeremy', 'Sarmiento', 'M', '60', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Leandro', 'Trossard', 'M', '11', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Aaron', 'Connolly', 'A', '7', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jurgen', 'Locadia', 'A', '27', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Neal', 'Maupay', 'A', '9', 4, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Danny', 'Welbeck', 'A', '18', 4, 0, 0, 0, 0, 0)

--Burnley

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nick', 'Pope', 'D', '1', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nathan Michael', 'Collins', 'V', '22', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Matthew', 'Lowton', 'V', '2', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ben', 'Mee', 'V', '6', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Erik', 'Pieters', 'V', '23', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Connor', 'Roberts', 'V', '14', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('James', 'Tarkowski', 'V', '5', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Charlie', 'Taylor', 'V', '3', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Josh', 'Brownhill', 'M', '8', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jack', 'Cork', 'M', '4', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Johann', 'Gudmundsson', 'M', '7', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Aaron', 'Lennon', 'M', '17', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Dwight', 'McNeil', 'M', '11', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ashley', 'Westwood', 'M', '18', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ashley', 'Barnes', 'A', '10', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Maxwel', 'Cornet', 'A', '20', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jay', 'Rodriguez ', 'A', '19', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Matej', 'Vydra', 'A', '27', 5, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Chris', 'Wood', 'A', '9', 5, 0, 0, 0, 0, 0)

--Chelsea

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kepa', 'Arrizabalaga', 'D', '1', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Edouard', 'Mendy', 'D', '16', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marcos', 'Alonso', 'V', '3', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Cesar', 'Azpilicueta', 'V', '28', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Trevoh', 'Chalobah', 'V', '14', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ben', 'Chilwell', 'V', '21', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Andreas', 'Christensen', 'V', '4', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Reece', 'James', 'V', '24', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Antonio', 'Rudiger', 'V', '2', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Malang', 'Sarr', 'V', '31', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Thiago', 'Silva', 'V', '6', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ross', 'Barkley', 'M', '18', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kai', 'Havertz', 'M', '29', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Callum', 'Hudson-Odoi', 'M', '20', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Jorginho', 'M', '5', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('N Golo', 'Kante', 'M', '7', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mateo', 'Kovacic', 'M', '8', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ruben', 'Loftus-Cheek', 'M', '12', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mason', 'Mount', 'M', '19', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Saul', 'Niguez', 'M', '17', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Christian', 'Pulisic', 'M', '10', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Hakim', 'Ziyech', 'M', '22', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Romelu', 'Lukaku', 'A', '9', 6, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Timo', 'Werner', 'A', '11', 6, 0, 0, 0, 0, 0)

--Crystal Palace

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jack', 'Butland', 'D', '1', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Guaita', 'D', '13', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joachim', 'Andersen', 'V', '16', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nathaniel', 'Clyne', 'V', '17', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marc', 'Guehi', 'V', '6', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tyrick', 'Mitchell', 'V', '3', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jairo', 'Riedewald', 'V', '44', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('James', 'Tomkins', 'V', '5', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joel', 'Ward', 'V', '2', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Eberechi', 'Eze', 'M', '10', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Conor', 'Gallagher', 'M', '23', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Will', 'Hughes', 'M', '12', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Cheikhou', 'Kouyate', 'M', '8', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('James', 'McArthur', 'M', '18', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Luka', 'Milivojevic', 'M', '4', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Michael', 'Olise', 'M', '7', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jesuran', 'Rak-Sakyi', 'M', '11', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jeffrey', 'Schlupp', 'M', '15', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jordan', 'Ayew', 'A', '9', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Christian', 'Benteke', 'A', '20', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Odsonne', 'Edouard', 'A', '22', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jean-Philippe', 'Mateta', 'A', '14', 7, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Wilfried', 'Zaha', 'A', '11', 7, 0, 0, 0, 0, 0)

--Everton

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Asmir', 'Begovic', 'D', '15', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jordan', 'Pickford', 'D', '1', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jarrad', 'Branthwaite', 'V', '32', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Seamus', 'Coleman', 'V', '23', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Lucas', 'Digne', 'V', '12', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ben', 'Godfrey', 'V', '22', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mason', 'Holgate', 'V', '4', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Michael', 'Keane', 'V', '5', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jonjoe', 'Kenny', 'V', '2', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Yerry', 'Mina', 'V', '13', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Allan', 'M', '6', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tom', 'Davies', 'M', '26', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Fabian', 'Delph', 'M', '8', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Abdoulaye', 'Doucoure', 'M', '16', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jean-Philippe', 'Gbamin', 'M', '25', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Andre', 'Gomes ', 'M', '21', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tyler', 'Onyango', 'M', '62', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ellis', 'Simms', 'M', '50', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Andros', 'Townsend', 'M', '14', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Dominic', 'Calvert-Lewin', 'A', '9', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Lewis', 'Dobbin', 'A', '61', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Anthony', 'Gordon', 'A', '24', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Demarai', 'Gray', 'A', '11', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Alex', 'Iwobi', 'A', '17', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Richarlison', 'A', '7', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Salomon', 'Rondon', 'A', '33', 8, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Cenk', 'Tosun', 'A', '20', 8, 0, 0, 0, 0, 0)

--Leeds United

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Illan', 'Meslier', 'D', '1', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Luke', 'Ayling ', 'V', '2', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Liam', 'Cooper', 'V', '6', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Charlie', 'Cresswell', 'V', '35', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Stuart', 'Dallas', 'V', '15', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Cody', 'Drameh', 'V', '37', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Junior', 'Firpo', 'V', '3', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Robin', 'Koch', 'V', '5', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Diego', 'Llorente', 'V', '14', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pascal', 'Struijk', 'V', '21', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Adam', 'Forshaw', 'M', '4', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Sam', 'Greenwood', 'M', '9', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jack', 'Harrison', 'M', '22', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Daniel', 'James', 'M', '20', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mateusz', 'Klich', 'M', '43', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Stuart', 'McKinstry', 'M', '14', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kalvin', 'Phillips', 'M', '23', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jamie', 'Shackleton', 'M', '46', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Patrick', 'Bamford', 'A', '9', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joe', 'Gelhardt', 'A', '30', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Liam', 'McCarron', 'A', '3', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Raphinha', 'A', '10', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tyler', 'Roberts', 'A', '11', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Rodrigo', 'A', '19', 9, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Crysencio', 'Summerville', 'A', '38', 9, 0, 0, 0, 0, 0)

--Leicester City

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kasper', 'Schmeichel', 'D', '1', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ryan', 'Bertrand', 'V', '5', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Timothy', 'Castagne', 'V', '27', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jonny', 'Evans', 'V', '6', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ricardo', 'Pereira', 'V', '21', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Caglar', 'Soyuncu', 'V', '4', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jannik', 'Vestergaard', 'V', '23', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marc', 'Albrighton', 'M', '11', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Daniel', 'Amartey', 'M', '18', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Harvey', 'Barnes', 'M', '7', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Hamza', 'Choudhury', 'M', '20', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kiernan', 'Dewsbury-Hall', 'M', '22', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('James', 'Maddison', 'M', '10', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Wilfred', 'Ndidi', 'M', '25', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Boubakary', 'Soumare', 'M', '42', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Luke', 'Thomas', 'M', '33', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Youri', 'Tielemans', 'M', '8', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Patson', 'Daka', 'A', '29', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kelechi', 'Iheanacho', 'A', '14', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ademola', 'Lookman', 'A', '37', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kasey', 'McAteer', 'A', '49', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ayoze', 'Perez', 'A', '17', 10, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jamie', 'Vardy', 'A', '9', 10, 0, 0, 0, 0, 0)

--Liverpool

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Alisson', 'D', '1', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Caoimhin', 'Kelleher', 'D', '62', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Trent', 'Alexander-Arnold', 'V', '66', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joe', 'Gomez', 'V', '12', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ibrahima', 'Konate', 'V', '5', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joel', 'Matip', 'V', '32', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Andrew', 'Robertson', 'V', '26', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Konstantinos', 'Tsimikas', 'V', '21', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Neco', 'Williams', 'V', '76', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Virgil', 'van Dijk', 'V', '4', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Fabinho', 'M', '3', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jordan', 'Henderson', 'M', '14', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Curtis', 'Jones', 'M', '17', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Naby', 'Keita', 'M', '8', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('James', 'Milner', 'M', '7', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tyler', 'Morton', 'M', '80', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Alex', 'Oxlade-Chamberlain', 'M', '15', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Thiago', 'M', '6', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Diogo', 'Jota', 'A', '20', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Harvey', 'Elliott', 'A', '67', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Roberto', 'Firmino', 'A', '9', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Sadio', 'Mane', 'A', '10', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Takumi', 'Minamino', 'A', '18', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Divock', 'Origi', 'A', '27', 11, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mohamed', 'Salah', 'A', '11', 11, 0, 0, 0, 0, 0)

--Manchester City

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Ederson', 'D', '31', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Zackary', 'Steffen', 'D', '13', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nathan', 'Ake', 'V', '6', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joao', 'Cancelo', 'V', '27', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ruben', 'Dias', 'V', '3', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Aymeric', 'Laporte', 'V', '14', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Benjamin', 'Mendy', 'V', '22', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('John', 'Stones', 'V', '5', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kyle', 'Walker', 'V', '2', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Oleksandr', 'Zinchenko', 'V', '11', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kevin', 'De Bruyne', 'M', '17', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Fernandinho', 'M', '25', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Phil', 'Foden', 'M', '47', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jack', 'Grealish', 'M', '10', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ilkay', 'Gundogan', 'M', '8', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('James', 'McAtee', 'M', '11', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Cole', 'Palmer', 'M', '80', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Rodri', 'M', '16', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bernardo', 'Silva', 'M', '20', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Gabriel', 'Jesus', 'A', '9', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Riyad', 'Mahrez', 'A', '26', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Raheem', 'Sterling', 'A', '7', 12, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ferran', 'Torres', 'A', '21', 12, 0, 0, 0, 0, 0)

--Manchester United

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('David', 'de Gea', 'D', '1', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Eric', 'Bailly', 'V', '3', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Diogo', 'Dalot', 'V', '20', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Victor', 'Lindelof', 'V', '2', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Harry', 'Maguire', 'V', '5', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Luke', 'Shaw', 'V', '23', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Alex', 'Telles', 'V', '27', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Raphael', 'Varane', 'V', '19', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Aaron', 'Wan-Bissaka', 'V', '29', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bruno', 'Fernandes', 'M', '18', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Fred', 'M', '17', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jesse', 'Lingard', 'M', '14', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nemanja', 'Matic', 'M', '31', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Scott', 'McTominay', 'M', '39', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Paul', 'Pogba', 'M', '6', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Donny', 'van de Beek', 'M', '34', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Edinson', 'Cavani', 'A', '21', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Anthony', 'Elanga', 'A', '36', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mason', 'Greenwood', 'A', '11', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Anthony', 'Martial', 'A', '9', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Marcus', 'Rashford', 'A', '10', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Cristiano', 'Ronaldo', 'A', '7', 13, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jadon', 'Sancho', 'A', '25', 13, 0, 0, 0, 0, 0)

--Newcastle United

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Karl', 'Darlow', 'D', '26', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Martin', 'Dubravka', 'D', '1', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Frederick', 'Woodman', 'D', '27', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ciaran', 'Clark', 'V', '2', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Federico', 'Fernandez', 'V', '18', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Emil', 'Krafth', 'V', '17', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jamaal', 'Lascelles', 'V', '6', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Javier', 'Manquillo', 'V', '19', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Fabian', 'Schar', 'V', '5', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Miguel', 'Almiron', 'M', '24', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ryan', 'Fraser', 'M', '21', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Isaac', 'Hayden', 'M', '14', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jeff', 'Hendrick', 'M', '16', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jamal', 'Lewis', 'M', '12', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Sean', 'Longstaff', 'M', '36', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Matt', 'Ritchie', 'M', '11', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Allan', 'Saint-Maximin', 'M', '10', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jonjo', 'Shelvey', 'M', '8', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joe', 'Willock', 'M', '28', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Dwight', 'Gayle', 'A', '34', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Joelinton', 'A', '7', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jacob', 'Murphy', 'A', '23', 14, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Callum', 'Wilson', 'A', '9', 14, 0, 0, 0, 0, 0)

--Norwich

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tim', 'Krul', 'D', '1', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('James Maximillian', 'Aarons', 'V', '2', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Samuel', 'Byram', 'V', '3', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Dimitris', 'Giannoulis', 'V', '30', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Benjamin', 'Gibson', 'V', '4', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Grant', 'Hanley', 'V', '5', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ozan', 'Kabak', 'V', '15', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Andrew', 'Omobamidele', 'V', '44', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Brandon', 'Williams', 'V', '21', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Todd', 'Cantwell', 'M', '14', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kieran', 'Dowell', 'M', '10', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Billy', 'Gilmour', 'M', '8', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pierre', 'Lees Melou', 'M', '20', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kenny', 'McLean', 'M', '23', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bali', 'Mumba', 'M', '26', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mathias', 'Normann', 'M', '16', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Przemyslaw', 'Placheta', 'M', '11', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Milot', 'Rashica', 'M', '17', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Lukas', 'Rupp', 'M', '7', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jacob Lungi', 'Sorensen', 'M', '19', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Adam', 'Idah', 'A', '35', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Teemu', 'Pukki', 'A', '22', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joshua', 'Sargent', 'A', '24', 15, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Christos', 'Tzolis', 'A', '18', 15, 0, 0, 0, 0, 0)

--Southampton

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Wilfredo', 'Caballero', 'D', '13', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Alex', 'McCarthy', 'D', '1', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jan', 'Bednarek', 'V', '35', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Valentino', 'Livramento', 'V', '21', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Lyanco', 'V', '4', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Romain', 'Perraud', 'V', '15', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mohammed', 'Salisu', 'V', '22', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jack', 'Stephens', 'V', '5', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kyle', 'Walker-Peters', 'V', '2', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Stuart', 'Armstrong', 'M', '17', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ibrahima', 'Diallo', 'M', '27', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Moussa', 'Djenepo', 'M', '19', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nathan', 'Redmond', 'M', '11', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Oriol', 'Romeu', 'M', '6', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('William', 'Smallbone', 'M', '20', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nathan', 'Tella', 'M', '23', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('James', 'Ward-Prowse', 'M', '8', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Che', 'Adams', 'A', '10', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Adam', 'Armstrong', 'A', '9', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Armando', 'Broja', 'A', '18', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mohamed', 'Elyounoussi', 'A', '24', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Shane', 'Long', 'A', '7', 16, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Theo', 'Walcott', 'A', '32', 16, 0, 0, 0, 0, 0)

--Tottenham Hotspur

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Hugo', 'Lloris', 'D', '1', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ben', 'Davies', 'V', '33', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Matt', 'Doherty', 'V', '2', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Royal', 'Emerson', 'V', '12', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Sergio', 'Reguilon', 'V', '3', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joe', 'Rodon', 'V', '14', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Gabriel Cristian', 'Romero', 'V', '4', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Davinson', 'Sanchez', 'V', '6', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ryan', 'Sessegnon', 'V', '19', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Japhet', 'Tanganga', 'V', '25', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Dele', 'Alli', 'M', '20', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Steven', 'Bergwijn', 'M', '23', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Eric', 'Dier', 'M', '15', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pierre-Emile', 'Hojbjerg', 'M', '5', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Giovani', 'Lo Celso', 'M', '18', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Lucas Moura', 'M', '27', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tanguy', 'Ndombele', 'M', '28', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Oliver', 'Skipp', 'M', '29', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Harry', 'Winks', 'M', '8', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Bryan', 'Gil', 'A', '11', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Harry', 'Kane', 'A', '10', 17, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Heung-Min', 'Son', 'A', '7', 17, 0, 0, 0, 0, 0)

--Watford

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Daniel', 'Bachmann', 'D', '26', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ben', 'Foster', 'D', '1', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Craig', 'Cathcart', 'V', '15', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Christian', 'Kabasele', 'V', '27', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Kiko', 'V', '21', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Adam', 'Masina', 'V', '11', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nicolas', 'N Koulou', 'V', '13', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jeremy', 'Ngakia', 'V', '2', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Danny', 'Rose', 'V', '3', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Francisco', 'Sierralta', 'V', '31', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('William', 'Troost-Ekong', 'V', '5', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tom', 'Cleverley', 'M', '8', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Oghenekaro', 'Etebo', 'M', '4', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Dan', 'Gosling', 'M', '16', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Juraj', 'Kucka', 'M', '33', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Imran', 'Louza', 'M', '6', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ken', 'Sema', 'M', '12', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Moussa', 'Sissoko', 'M', '19', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ozan', 'Tufan', 'M', '18', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Cucho', 'A', '29', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Emmanuel', 'Dennis', 'A', '25', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ashley', 'Fletcher', 'A', '17', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joshua', 'King', 'A', '7', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joao', 'Pedro', 'A', '10', 18, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ismaila', 'Sarr', 'A', '23', 18, 0, 0, 0, 0, 0)

--West Ham United

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Lukasz', 'Fabianski', 'D', '1', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Harrison', 'Ashby', 'V', '50', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Vladimir', 'Coufal', 'V', '5', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Aaron', 'Cresswell', 'V', '3', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Craig', 'Dawson', 'V', '15', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Issa', 'Diop', 'V', '23', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ryan', 'Fredericks', 'V', '24', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Benjamin', 'Johnson', 'V', '31', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Arthur', 'Masuaku', 'V', '26', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Angelo', 'Ogbonna', 'V', '21', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Kurt', 'Zouma', 'V', '4', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Said Mohamed', 'Benrahma', 'M', '22', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Pablo', 'Fornals', 'M', '8', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Manuel', 'Lanzini', 'M', '10', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Mark', 'Noble', 'M', '16', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Declan', 'Rice', 'M', '41', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Tomas', 'Soucek', 'M', '28', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nikola', 'Vlasic', 'M', '11', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Michail', 'Antonio', 'A', '9', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jarrod', 'Bowen', 'A', '20', 19, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Andriy', 'Yarmolenko', 'A', '7', 19, 0, 0, 0, 0, 0)

--Wolverhampton Wanderers

INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Jose', 'Sa', 'D', '1', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Rayan', 'Ait Nouri', 'V', '3', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Conor', 'Coady', 'V', '16', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ki-Jana', 'Hoever', 'V', '2', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Max', 'Kilman', 'V', '23', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Fernando', 'Marcal', 'V', '5', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Romain', 'Saiss', 'V', '27', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Nelson', 'Semedo', 'V', '22', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Leander', 'Dendoncker', 'M', '32', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Joao', 'Moutinho', 'M', '28', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Ruben', 'Neves', 'M', '8', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Hee-Chan', 'Hwang', 'A', '26', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Raul', 'Jimenez', 'A', '9', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Daniel', 'Podence', 'A', '10', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Fabio', 'Silva', 'A', '17', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('Adama', 'Traore', 'A', '37', 20, 0, 0, 0, 0, 0)
INSERT INTO Spelers (Voornaam, Achternaam, Positie, Rugnummer, ClubID, Doelpunt, Assist, GeleKaart, RodeKaart, Owngoal) VALUES ('', 'Trincao', 'A', '11', 20, 0, 0, 0, 0, 0)
